### ISSUE TITLE
[feature request]: allow users to customize the output string using the gotemplates

### ISSUE THREAD

**Issue by leonsteinhaeuser** [urbanmedia/passbolt-operator#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently, it is not possible to create a secret field that contains a custom connection string like database `dsn` strings. This feature might be required for applications to retrieve and set certain settings.

### Describe the solution you'd like:

```yaml
apiVersion: passbolt.tagesspiegel.de/v1alpha1
kind: PassboltSecret
metadata:
  name: passboltsecret-sample
spec:
  leaveOnDelete: false
  secrets:
    - kubernetesSecretKey: s3_endpoint
      passboltSecret:
         name: S3_EXAMPLE
         field: uri
    - kubernetesSecretKey: dsn
      passboltSecret:
         name: APP_EXAMPLE
         template: postgresql://{{.Username}}@{{.URL}}/mydatabase?sslmode=disable?password={{.Password}}
```

### Describe alternatives you've considered

Not every application supports configuring the database, password and username in a separate field. Since we do not support such things yet, we should think about it.
